name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1

    - name: NPM Install 
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@13046b614c663b56cba4dda3f30b9736a748b80d
      with:
        branch: gh-pages
        folder: build
