name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1

    - name: Configure Git
      run: git config --global user.email "bot@iamabot.com" && git config --global user.name "Super Deployer Bot - LOL"

    - name: NPM Install 
      run: npm install
    
    - name: Build
      run: npm run deploy
